version: "3.1"
services:

    mariadb:
      container_name: mariadb-server
      restart: always
      image: mariadb:latest
      expose:
        - "3406"
      ports:
        - "3406:3406"
      env_file:
        - variables.env

    app:
      container_name: phalcon-server
      build: docker/app
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./phpconfig:/usr/local/etc/php
        - ./rafflePrizes/app:/var/www/html/app
        - ./rafflePrizes/public:/var/www/html
        - ./vendor:/var/www/html/vendor
      depends_on:
        - mariadb

      

