<?php

/**
 * @var RafflePrizes\forms\AuthForm $form
 */
?>

<p style="color: red"><?php $this->flash->output() ?></p>

<form action="" method="post">

    <div class="form-group">
        <label>Ваш e-mail</label>
        <?= $form->render('email') ?>
    </div>
    <div class="form-group">
        <label>Ваш пароль</label>
        <?= $form->render('password') ?>
    </div>

    <input type="submit" name="apply" value="Применить" class="btn btn-success">
</form>

