<?php

use RafflePrizes\routes\AuthRoute;

/**
 * @var RafflePrizes\forms\AuthForm $form
 */
?>

<p style="color: red"><?php $this->flash->output() ?></p>

<form action="" method="post">

    <div class="form-group">
        <label>Ваше имя</label>
        <?= $form->render('name') ?>
    </div>
    <div class="form-group">
        <label>Ваш e-mail</label>
        <?= $form->render('email') ?>
    </div>
    <div class="form-group">
        <label>Ваш пароль</label>
        <?= $form->render('password') ?>
    </div>

    <input type="submit" name="apply" value="Регистрация" class="btn btn-success">
    <br>
    <a href="<?= AuthRoute::ROUTE_AUTH ?>">Войти</a>
</form>

